version: "3"
services:
  app:
    container_name: aerohappy
    image: node:dubnium
    volumes:
      - ./:/src
    working_dir: /src
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    command: npm run start:dev
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
