export default {
  GET_COUNTRY: 'GET_COUNTRY',
  SET_COUNTRY: 'SET_COUNTRY',
  SET_CITY_ID: 'SET_CITY_ID',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  SET_ERROR: 'SET_ERROR',
};
